### ISSUE TITLE
Move Client Side SSL Certificates to Cert-Manager

### ISSUE THREAD

**Issue by khatrivarun** [PhotoAtom/postgres#37]
# Objectives:
 - Move away all certificate management from CloudNative PG to Cert-Manager
 - For Server CA: https://cloudnative-pg.io/documentation/1.24/certificates/#cert-manager-example
 - For Replication Certificates: https://cloudnative-pg.io/documentation/1.24/certificates/#cert-manager-example_1
 - For User Certificates: Refer to the example given below

# Example for User Certificate Management using Cert-Manager

User Certificate Generation Example YAML:

```
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: server-ca
spec:
  isCA: true
  commonName: my-selfsigned-server-ca
  secretName: server-ca-key-pair
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: server-ca-issuer
spec:
  ca:
    secretName: server-ca-key-pair
---
apiVersion: v1
kind: Secret
metadata:
  name: my-postgres-server-cert
  labels:
    cnpg.io/reload: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-postgres-server-cert
spec:
  secretName: my-postgres-server-cert
  usages:
    - server auth
  dnsNames:
    - cluster-example-lb.internal.mydomain.net
    - cluster-example-rw
    - cluster-example-rw.default
    - cluster-example-rw.default.svc
    - cluster-example-r
    - cluster-example-r.default
    - cluster-example-r.default.svc
    - cluster-example-ro
    - cluster-example-ro.default
    - cluster-example-ro.default.svc
  issuerRef:
    name: server-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: client-ca
spec:
  isCA: true
  commonName: my-selfsigned-client-ca
  secretName: client-ca-key-pair
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: client-ca-issuer
spec:
  ca:
    secretName: client-ca-key-pair
---
apiVersion: v1
kind: Secret
metadata:
  name: my-postgres-client-cert
  labels:
    cnpg.io/reload: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: my-postgres-client-cert
spec:
  secretName: my-postgres-client-cert
  usages:
    - client auth
  commonName: streaming_replica
  issuerRef:
    name: client-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: keycloak-postgres-client-cert
spec:
  secretName: keycloak-postgres-client-cert
  usages:
    - client auth
  commonName: keycloak
  issuerRef:
    name: client-ca-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: v1
data:
  username: a2V5Y2xvYWs=
  password: a2V5Y2xvYWs=
kind: Secret
metadata:
  name: cluster-example-keycloak
  labels:
    cnpg.io/reload: "true"
type: kubernetes.io/basic-auth
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cluster-example
spec:
  managed:
    roles:
    - name: keycloak
      ensure: present
      comment: Keycloak User
      login: true
      superuser: false
      passwordSecret:
        name: cluster-example-keycloak
  instances: 1
  postgresql:
    pg_hba:
      - hostssl app all all cert
  certificates:
    serverTLSSecret: my-postgres-server-cert
    serverCASecret: my-postgres-server-cert
    clientCASecret: my-postgres-client-cert
    replicationTLSSecret: my-postgres-client-cert
  storage:
    size: 1Gi
---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: cluster-example-one
spec:
  name: keycloak
  owner: keycloak
  cluster:
    name: cluster-example

```

Command to check connection:
```
 psql "sslmode=verify-ca sslrootcert=ca.crt sslcert=tls.crt sslkey=tls.key hostaddr=127.0.0.1 port=5436 user=keycloak dbname=keycloak"
```
Where:
 - `ca.crt` is the `my-selfsigned-server-ca` certificate
 - `tls.crt` and `tls.key` is from `keycloak-postgres-client-cert`
